export const FETCH_MIN_LIST_START = 'FETCH_MIN_LIST_START'
export const FETCH_MAX_LIST_START = 'FETCH_MAX_LIST_START'
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL'

export const FETCH_MIN_LIST = 'FETCH_MIN_LIST'
export const FETCH_MAX_LIST = 'FETCH_MAX_LIST'


